
CREATE TABLE "user" (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        first_name VARCHAR(255) NOT NULL,
                        last_name VARCHAR(255) NOT NULL,
                        CONSTRAINT pk_user PRIMARY KEY (id)
);
CREATE INDEX idx_user_name ON "user" (first_name, last_name);

CREATE TABLE post (
                      id SERIAL PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      text VARCHAR(10000) NOT NULL,
                      created_at TIMESTAMP WITHOUT TIME ZONE,
                      published_at TIMESTAMP WITHOUT TIME ZONE,
                      user_id BIGINT REFERENCES "user" (id),
                      CONSTRAINT fk_post_on_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

ALTER TABLE "user"
    ADD email VARCHAR(255);

ALTER TABLE "user"
    ADD last_activity TIMESTAMP WITHOUT TIME ZONE;

CREATE VIEW user_statistics AS
SELECT u.id as user_id,
       count(p.id) as number_of_posts
FROM "user" u
         JOIN post p on u.id = p.user_id
GROUP BY u.id;
